### PR TITLE
Create build.sbt in root directory

### PR DESCRIPTION
**Pull request by jiminhsieh**
1. Create build.sbt in root directory 
2. Rename each folder of subproject
3. Move build.sbt of subproject to root
4. Update Scala to 2.11.11
5. Update Akka to 2.4.18

I think it would easier to read the whole subproject. You don't need to open project by project. You can just open root project.

### CODE REVIEW

**Comment by johanjanssen** [comment]
Thanks a lot for your time and effort. I've looked at the pull request and I have two questions:
- Why did you remove the Scheduler example 'Scheduler/src/main/scala/com/example/Startup.scala'?
- How can I run the command alias for the code quality project? sbt [projectname]/run works, but sbt [projectname]/tests which is the command alias does not work.

**Comment by jiminhsieh** [comment]
Thanks for your reviewing!

* That's a mistake to remove `Scheduler/src/main/scala/com/example/Startup.scala`. I will recover it.
* It's a bug. I will try to fix it soon.

**Comment by jiminhsieh** [comment]
Is sbt has `sbt tests`? I only see `sbt test`. I guess it's just typo, so it didn't work.

**Comment by johanjanssen** [comment]
'tests' is an alias defined in the build.sbt, see below. However I couldn't manage to trigger the 'tests' or the 'static' command. Maybe I simply don't use the correct sbt statement, do you know how to run 'tests' or 'static'?

lazy val `two-actors-code-quality` = project
  .settings(commonSettings,
....
    addCommandAlias("tests", ";clean ;coverage ;test ;coverageReport"),
    addCommandAlias("static", ";scalastyle ;scapegoat ;stats")
  )

**Comment by jiminhsieh** [comment]
Thanks for your correction. I got it. I found it can work with `sbt "project two-actors-code-quality" tests`. But it still not work with the origin command. I will try to find out the solution.

**Comment by johanjanssen** [comment]
Thanks a lot! I just merged your pull request.

**Pull request merged**
